<?php
$form = $this->form;
$form->get('idReporte911');
$idSolicitud = $this->paciente->getIdSolicitud();
$form->get('solicitudIngreso_idSolicitud')->setAttributes([
    'value' => $idSolicitud,
    'placeholder' => 'Operadora'
]);

$form->get('operadora')->setAttributes([
    'class' => 'span2 m-wrap',
    'placeholder' => 'Operadora'
]);
$form->get('folio')->setAttributes([
    'class' => 'span1 m-wrap',
    'placeholder' => 'Folio'
]);
$form->get('vehiculos_idvehiculos')->setAttributes([
    'class' => 'span2 m-wrap',
    'style' => '',
    'id' => 'vehiculos_idvehiculos',
    'placeholder' => ''
]);
$form->get('observaciones')->setAttributes([
    'class' => 'span4 m-wrap',
    'placeholder' => 'observaciones'
]);

$form->get('submit')->setAttributes(array('class' => 'span2 m-wrap btn btn-primary '));
$form->prepare();
?>


<div id="content-header">
    <div id="breadcrumb"> <a href="<?= $this->url('home') ?> " title="Panel" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="<?= $this->url('expedientes') ?>">Pacientes</a>  <a href="<?= $this->url('expedientes') ?>">Solicitud Ingreso</a> <a href="<?= $this->url('expedientes') ?>">Reporte 911</a> </div>
    <h1><?= $this->titulo; ?></h1>
    <div class="container-fluid"> 
        <p><?= $this->subTitulo; ?></p> 
    </div> 

</div>
<div class="container-fluid"><hr>
    <div class="widget-box widget-plain">
        <div class="center">
            <ul class="stat-boxes2">
                <li>
                    <div class="right" title="Solicitude del paciente"> <strong><?= $this->countSolicitud ?></strong> Solicitudes </div>
                </li>

            </ul>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-briefcase"></i> </span>
                    <h5>Detalle del Prospecto</h5>
                </div>
                <div class="widget-content">
                    <div class="row-fluid">
                        <div class="span6">
                            <table>
                                <tbody>
                                    <tr>
                                        <td><h3><?= $this->paciente->getNombrePaciente() ?></h3></td>
                                    </tr>
                                    <tr>
                                        <td><h5>Sexo: <?= $this->paciente->getSexo() ?> Edad:  <?= $this->paciente->getEdad() ?></h5></td>
                                    </tr>
                                    <tr>
                                        <td><h5>Responsable: <?= $this->paciente->getNombreFamiliar() ?></h5> Parentesco: <?= $this->paciente->getParentesco() ?></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td><h5><strong>Teléfono Cel.: +<?= $this->paciente->getTelefono() ?></strong></h5></td>
                                    </tr>
                                    <tr>
                                        <td><h5>Direccion: <strong><?= $this->paciente->getDomicilio() ?></strong> <br>
                                                <?= $this->paciente->getColonia() . ' ' . $this->paciente->getMunicipio() ?>, <br></h5></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="span6">

                            <table class="table table-bordered table-invoice">
                                <tbody>
                                    <tr>
                                    </tr><tr>
                                        <td class="width30">RFC:</td>
                                        <td class="width70"><strong><?= $this->paciente->getRFC() ?></strong></td>
                                    </tr>
                                    <tr>
                                        <td>Fecha Solicitud:</td>
                                        <td><strong><?= $this->paciente->getFechaSolicitud() ?></strong></td>
                                    </tr>                                                
                                    <tr><td class="width30">Tipo Solicitud:</td>
                                        <td class="width70">
                                            <strong><?= $this->paciente->getTipoSolicitud() ?></strong></td>
                                    </tr>
                                </tbody>

                            </table>
                        </div>
                    </div>
                    <div id="message-text">
                        <div id="cargando">
                        </div>
                    </div>

                        
                    
                    <?= $this->formElementErrors($form->get('vehiculos_idvehiculos')); ?> 
                    <?= $this->formElementErrors($form->get('folio')); ?>
                    <?= $this->formElementErrors($form->get('operadora')); ?>
                    <?= $this->formElementErrors($form->get('observaciones')); ?>
                </div>
                <hr>
                <div class="row-fluid">
                    <div class="widget-box">
                        <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                            <h5>Alta del Reporte 911</h5>
                        </div>
                        <?= $this->form()->openTag($form); ?>
                        <div class="widget-content">
                            <div class="controls controls-row">

                                <?= $this->formElement($form->get('solicitudIngreso_idSolicitud')); ?>
              
                               
                                <!--                <div data-date="12-02-2012" class="input-append date datepicker">
                                                  <input type="text" value="12-02-2012" data-date-format="mm-dd-yyyy" class="span11">
                                                  <span class="add-on"><i class="icon-th"></i></span> </div>-->

                                <?= $this->formElement($form->get('vehiculos_idvehiculos')); ?>

                                <?= $this->formElement($form->get('folio')); ?>

                                <?= $this->formElement($form->get('operadora')); ?>

                                <?= $this->formElement($form->get('observaciones')); ?> 

                                <?= $this->formElement($form->get('submit')); ?>
                            </div>
                        </div>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                   

                </div>
            </div>
        </div>
    </div>
</div>
