<div id="content-header">
    <div id="breadcrumb"> <a href="<?= $this->url('home') ?> " title="Panel" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="<?= $this->url('expedientes') ?>">Expediente</a><a href="<?= $this->url('expedientes') ?>">Contrato</a></div>
    <h1><?= $this->titulo; ?></h1>
</div>


<div class="container-fluid">                 
    <hr>
    <?PHP
    echo $this->flashMessenger()
            ->setMessageOpenFormat('<div class="alert alert-info alert-block"> <a class="close" data-dismiss="alert" href="#">×</a><h1>El registro se ha Guardado!</h1>')
            ->setMessageSeparatorString('<p></p>')
            ->setMessageCloseString('</div>')
            ->render('success');
    ?>
    <?php
    echo $this->controlador;
    ?>
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
            <h5>Data table</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>N° Expediente</th>
                        <th>Nombre</th>
                        <th>Estancia</th>
                        <th>Costo Tratamiento</th>
                        <th>Pago Ingreso</th>
                        <th>Plazo</th>
                        <th>Pago</th>
                        <th>Fecha Contrato</th>
                        <th>Fecha Expediente</th> 
                        
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->objContrato as $obj): ?>
                        <tr class="gradeX">
                            <td><?= $obj['numeroExpediente'] ?></td>
                            <td><?= $obj['nombre'] ?></td>
                            <td><?= $obj['tiempo'] ?></td>
                            <td>$<?= $obj['costoTratamiento'] ?></td>
                            <td>$<?= $obj['pagoIngreso'] ?></td>
                            <td><?= $obj['plazo'] ?></td>
                            <td>$<?= $obj['cantidadPago'] ?></td>
                            <td><?= $obj['fechaContrato'] ?></td>
                            <td><?= $obj['fechaExpediente'] ?></td>                           
                            <td>
                                <a class="btn btn-primary" title="Editar solicitud" href="<?= $this->url('solicitud-modificar') ?>"><i class="icon-edit"></i></a></td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
