
    <h1 align="center">CONSENTIMIENTO INFORMADO</h1>
    <p class="text-primary" align="justify">
        No. de expediente:  <strong><?= $this->numeroExpediente ?></strong><br> 
        Por parte del familiar o representante legal o tutor:
        Por medio de la presente, yo: <strong><?= $this->nombreFam ?></strong>  declaro haber sido informado que el establecimiento Centro Renovación., ubicado en Blvd. Agustín de Vildosola 178 Col. Pedregal de La Villa ofrece un tratamiento residencial por un tiempo mínimo de 3 meses, que tiene la finalidad de brindar atención para el consumo de alcohol y/o drogas de mí: hijo, que lleva por nombre: <strong><?= $this->nombre ?></strong>  de sexo masculino, con: <strong><?= $this->edad ?></strong> años de edad. Dicho tratamiento se basa en un modelo de tratamiento mixto cuyo objetivo consiste en: Ayuda mutua mediante el programa de 12 pasos de alcohólicos anónimos y ayuda profesional por parte de Medico, Psiquiatra psicólogo y consejero en adicciones.

    </p><br>
    <p class="text-primary" align="justify">
        Estoy de acuerdo en participar activamente durante todo el proceso de tratamiento de mi familiar con la finalidad de lograr su abstinencia y facilitar su recuperación, lo cual implica asistir a las sesiones que el médico, psicólogo y/o consejero me indiquen. En caso necesario y al no obtener los resultados esperados, acepto que se me proporcione información por escrito respecto a otro tipo de alternativas de atención a donde pueda acudir mi familiar. Tengo conocimiento de que la relación entre mi familiar con el personal del establecimiento, será únicamente profesional. 
    </p><br>
    <p class="text-primary" align="justify">
        Por otra parte, me comprometo a cumplir con una cuota de  <strong>$<?= $this->costoTratamiento ?></strong> en beneficio de tener acceso a servicios dignos y apropiados durante mi estancia. En el caso de cancelar mi permanencia antes de haber cumplido con el período de tratamiento, estoy de acuerdo en cubrir los pagos del tratamiento en su totalidad. Ratifico que he sido informado respecto a las características del tratamiento, los procedimientos, los riesgos que implica, los costos, así como los beneficios esperados, y estoy de acuerdo en los requerimientos necesarios para su aplicación. 
    </p><br>
    <p class="text-primary" align="justify">
        <strong>Por parte del establecimiento: </strong><br>
        El establecimiento Centro Renovación. se compromete a brindar un servicio de atención de calidad que facilite la recuperación y la reinserción del usuario a una vida productiva, garantizando en todo momento el respeto a su integridad y haciendo valer sus derechos. Por ello, en el caso de que el usuario desee suspender el tratamiento antes de que éste finalice, el centro se compromete a no mantenerlo de forma involuntaria y a brindarle la información y la orientación necesaria para continuar con el proceso de rehabilitación en otra instancia.
    </p><br>
    <p class="text-primary" align="justify">
        Se pone de manifiesto cumplir en tiempo y forma con el pago de ingreso de <strong>$<?= $this->pagoIngreso ?></strong> y con <strong>$<?= $this->cantidadPago ?></strong> en un plazo <strong><?= $this->plazo ?></strong> y que toda información brindada por el usuario es de carácter confidencial y sólo tendrán acceso a ésta el equipo multidisciplinario involucrado en el proceso terapéutico, por lo que no se revelará a ningún otro individuo, si no es bajo el consentimiento escrito del usuario, exceptuando los casos previstos por la ley y autoridades sanitarias.
    </p><br>
    <p class="text-primary" align="justify">
        Así mismo, durante el tratamiento no se realizarán grabaciones de audio, video o fotografías, sin que el personal del establecimiento explique su finalidad y sin previo consentimiento escrito por parte del usuario.
    </p><br>
    <p class="text-primary" align="justify">
        En el caso de que el usuario presente una condición médica previa al ingreso, el establecimiento dará continuidad al tratamiento médico o farmacológico, suministrando los medicamentos en las dosis y horarios indicados, siempre y cuando éstos sean proporcionados por el médico de la institución o el enfermero capacitado y existan los estudios y recetas avaladas por un médico certificado y no se contraindique con el tratamiento recibido durante la estancia. En caso de que el usuario requiera estudios complementarios o el servicio de un médico especializado, se le informará al respecto y se dará aviso a los familiares. En el caso de que el usuario requiera atención médica urgente, se dará aviso inmediato a los familiares y se trasladará a algún hospital del segundo nivel de atención.
        Por otro lado, el establecimiento se exime de toda responsabilidad por los actos en contra de la ley en que el usuario se haya visto involucrado, previo y posterior al tratamiento.
    </p><br>
    <p class="text-primary" align="justify">
        En el caso de que el usuario o sus familiares presenten alguna duda respecto al proceso de rehabilitación o a cualquier otro asunto relacionado con el mismo, el establecimiento se compromete a aclararla y a proporcionar información relativa al estado de salud del usuario y evolución del tratamiento en cualquier momento que lo solicite.
        Finalmente, el establecimiento se compromete a proporcionar y a dar lectura del reglamento interno del establecimiento al usuario, familiar y/o responsable legal.
    </p><br>
    <p class="text-primary" align="justify">
        Siendo las _______hrs. del día ___________del mes ________ del año ________ en Hermosillo Sonora y habiendo sido informado y aceptando los compromisos anteriormente expuestos firman el presente consentimiento:
    </p><br>
    <p class="text-primary" align="justify">
        __________________________________                     ________________________________<br>
            Nombre y firma del usuario                             Nombre y firma del familiar
    </p>
    <p class="text-primary" align="justify">
        ___________________________                    ___________________________<br>
    Norme y firma del 1° testigo                           Nombre y firma del 2° testigo

    </p>
   