<div id="content-header">
    <div id="breadcrumb"> <a href="<?= $this->url('home') ?> " title="Panel" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="<?= $this->url('expedientes') ?>">Expediente</a></div>
    <h1><?= $this->titulo; ?></h1>
</div>


<div class="container-fluid">                 
    <hr>
    <?PHP

    echo $this->flashMessenger()
        ->setMessageOpenFormat('<div class="alert alert-info alert-block"> <a class="close" data-dismiss="alert" href="#">×</a><h1>El registro se ha Guardado!</h1>')
        ->setMessageSeparatorString('<p></p>')
        ->setMessageCloseString('</div>')
        ->render('success');
?>
    <?php
    echo $this->controlador;
    ?>
    <a class="btn btn-info" href="<?=$this->url('solicitud-nuevo')?>"><i class="icon-plus-sign"></i> Nuevo</a>
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
            <h5>Data table</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>R.F.C</th>
                        <th>Solicitante</th>
                        <th>Domicilio</th>
                        <th>Edad</th>                        
                        <th>Familiar</th>                        
                        <th>Estado</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->solicitud as $obj): ?>
                        <tr class="gradeX">
                            <td><?= $obj->getRFC() ?></td>
                            <td><?= $obj->getNombrePaciente() ?></td>
                            <td><?= $obj->getDomicilio() ?></td>
                            <td><?= $obj->getEdad() ?></td>
                            <td><?= $obj->getNombreFamiliar() ?></td>                            
                            <td><?= $obj->getEstado() ?> <img src="<?= $this->basePath('img/icons/16/calendar.png') ?>" ></td>
                            <td>
                                <a class="btn btn-primary" title="Editar solicitud" href="<?= $this->url('solicitud-modificar')?><?= '/'.$obj->getIdSolicitud() ?>"><i class="icon-edit"></i> </a>
                                <a class="btn btn-info" title="Detalle solicitud" href="<?= $this->url('solicitud-detalle')?><?= '/'.$obj->getIdSolicitud() ?><?= '/'.$obj->getRFC() ?>"><i class="icon-desktop"></i> </a>
                                <a class="btn btn-danger" title="Eliminar solicitud" href="#" ><i class="icon-remove"></i> </a>
                                
                        </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
