<?php
$form = $this->form;

$form->get('idproductos');

$form->get('codigo')->setAttributes([
    'class' => 'span3',
    'placeholder' => 'Código'
]);

$form->get('nombre')->setAttributes([
    'class' => 'span5 m-wrap',
    'placeholder' => 'Nombre',
]);

$form->get('unidadMedida')->setAttributes([
    'class' => 'control-label',
    'placeholder' => ''
]);

$form->get('precio')->setAttributes([
    'class' => 'span2',
    'pattern' => '(\d{3})([\.])(\d{2})',
    'placeholder' => '00.00'
]);

$form->get('descripcion')->setAttributes([
    'class' => 'span5',
    'placeholder' => 'Descripción'
]);

$form->get('submit')->setAttributes(array('class' => 'btn btn-primary'));
$form->prepare();
?>

<div id="content-header">
    <div id="breadcrumb"> <a href="<?= $this->url('home'); ?>" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="<?= $this->url('expedientes'); ?>">Inventario</a> <a href="#" class="current">Nuevo Producto</a> </div>
    <h1><?= $this->titulo; ?></h1>
</div>

<div class="container-fluid">  
    <div id="message-text"></div>
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Nuevo producto del Inventario</h5>
                </div>
                <div class="widget-content nopadding">
                    <?= $this->form()->openTag($form); ?>
                    <div class="control-group">
                        <?= $this->formLabel($form->get('codigo')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('codigo')); ?> 
                            <?= $this->formElementErrors($form->get('codigo')); ?>                          
                            <div class="hint">
                                (Código del Producto)</div>
                            </div>
                    </div>
                    <div class="control-group">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('nombre')); ?>
                            <?= $this->formElementErrors($form->get('nombre')); ?>

                        </div>
                    </div> 
                    <div class="control-group">                       
                        <?= $this->formLabel($form->get('unidadMedida')); ?>
                        <div class="controls">                             
                            <?= $this->formElement($form->get('unidadMedida')); ?>
                            <?= $this->formElementErrors($form->get('unidadMedida')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('precio')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('precio')); ?>
                            <?= $this->formElementErrors($form->get('precio')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('descripcion')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('descripcion')); ?>
                            <?= $this->formElementErrors($form->get('descripcion')); ?>

                        </div>
                    </div> 
                   

                    <div class="form-actions">
                        <?= $this->formElement($form->get('submit')); ?>
                        <input id="back" class="btn btn-danger" type="reset" value="Cancelar" />
                        <div id="status"></div>
                    </div>
                    <?= $this->form()->closeTag(); ?>


                </div>
            </div>
        </div>
    </div>
</div>
