<script>
    $("#image-form").on('submit', function (e) {
        e.preventDefault();
        $.ajax({
            type: "POST",
            url: '/cedemun/public/configuracion/nuevoajax',
            data: new FormData(this),
            contentType: false,
            cache: false,
            processData: false,
            beforeSend: function ()
            {
                $('.btnGuardarConfi').attr("disabled", "disabled");
                $('#image-form').css("opacity", ".5");
            },
            success: function (data)
            {
                console.log(data);

//                var listaUsuarios = $("#lista-usuarios");
//                $.each(respuesta.data, function (index, elemento) {
//                    listaUsuarios.append(
//                            '<div>'
//                            + '<p>' + elemento.first_name + ' ' + elemento.last_name + '</p>'
//                            + '<img src=' + elemento.avatar + '></img>'
//                            + '</div>'
//                            );
//                });
                var formulario = $("#formDep");
                formulario.html(data);

            },
            error: function () {
                console.log("No se ha podido obtener la información");
            }
        });
        alert('boton');
    });
    //file type validation
    $("#file").change(function () {
        var filename =document.getElementById("file").files[0].name;
        var file = this.files[0];
        var imagefile = file.type;
        var match = ["image/jpeg", "image/png", "image/jpg"];
     
        $("#logo_empresa").val(filename.toString());
    });

</script>

<h1>Image Gallery</h1>

<p>
  This page displays the list of uploaded images.
</p>

<p>
    <a href="" id="btnImg" class="btn btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo" role="button" aria-pressed="true">Nuevo</a>
  <a href="<?= $this->url('images', ['action'=>'upload']); ?>"
     class="btn btn-primary" role="button">Upload More</a>
</p>

<hr/>

<?php if(count($files)==0): ?>

<p>
  <i>There are no files to display.</i>
</p>

<?php else: ?>

<div class="row">
  <div class="col-sm-6 col-md-12">

    <?php foreach($files as $file): ?>

    <div class="img-thumbnail">

      <img src="<?= $this->url('images', ['action'=>'file'],
           ['query'=>['name'=>$file],'thumbnail'=>true]); ?>">

      <div class="caption">
        <h3><?php echo $file; ?></h3>
        <p>
        <a target="_blank" href="<?= $this->url('images', ['action'=>'file'],
           ['query'=>['name'=>$file]]); ?>"
           class="btn btn-default" role="button">Show in Natural Size</a>
        </p>
      </div>
    </div>

    <?php endforeach; ?>
  </div>
</div>

<?php endif; ?>

<hr/>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Nueva Empresa</h4>                


                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>           
            <div id="formDep" class="modal-body">

            </div>
           
        </div>
    </div>
</div>