<script>
    $("#image-form").on('submit', function (e) {
        e.preventDefault();
        $.ajax({
            type: "POST",
            url: '/cedemun/public/images/nuevoajax',
            data: new FormData(this),
            contentType: false,
            cache: false,
            processData: false,
            beforeSend: function ()
            {
                $('.btnGuardarConfi').attr("disabled", "disabled");
                $('#configuracion-form').css("opacity", ".5");
            },
            success: function (data)
            {
                console.log(data);

                var formulario = $("#formDep");
                formulario.html(data);

            },
            error: function () {
                console.log("No se ha podido obtener la información");
            }
        });
        alert('boton');
    });
    //file type validation
    $("#file").change(function () {
        var filename =document.getElementById("file").files[0].name;
        var file = this.files[0];
        var imagefile = file.type;
        var match = ["image/jpeg", "image/png", "image/jpg"];
     
        $("#logo_empresa").val(filename.toString());
    });

</script>
<?php
$form = $this->form;
$form->get('upload')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Upload a New Image</h1>

<p>
    Please fill out the following form and press the <i>Upload</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('file')); ?>
            <?= $this->formElement($form->get('file')); ?>
            <?= $this->formElementErrors($form->get('file')); ?>
            <div class="hint">(PNG and JPG formats are allowed)</div>
        </div>
         <div class="form-group">
            <?= $this->formLabel($form->get('logo_empresa')); ?>
            <?= $this->formElement($form->get('logo_empresa')); ?>
            <?= $this->formElementErrors($form->get('logo_empresa')); ?>
            <div class="hint">(PNG and JPG formats are allowed)</div>
        </div>
      

        <?= $this->formElement($form->get('upload')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>


