<div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="#">Form elements</a> <a href="#" class="current">Form wizard</a> </div>
    <h1><?= $this->titulo; ?></h1>
</div>

<div class="container-fluid"><hr>
    <h5><?= $this->subTitulo; ?></h5>                    
    <hr>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="<?= $this->url('nuevo') ?>" class="btn btn btn-danger btn-sm" role="button" aria-pressed="true">Nuevo</a>
            <a href="<?= $this->url('empleados') ?>" class="btn btn btn-danger btn-sm" role="button" aria-pressed="true">Export</a>
        </div>
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Departamentos</button>
    </div>
    <?php
    echo $this->controlador;
    ?>
    <div class="table-responsive"><br>
       
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Nueva departamento de la Institución</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Recipient:</label>
                            <input type="text" class="form-control" id="recipient-name">
                        </div>
                        <div class="form-group">
                            <label for="message-text" class="col-form-label">Message:</label>
                            <textarea class="form-control" id="message-text"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Send message</button>
                </div>
            </div>
        </div>
    </div>

    <div class="widget-box">
        <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
            <h5><?= $this->subTitulo; ?></h5>
            <span class="label label-info">Featured</span> </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nº Empleado</th>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Tipo Plaza</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                     <?php foreach ($this->empleados as $empleados): ?>
                    <tr>
                        <td><?= $empleados->getIdEmpleados() ?></td>
                        <td><?= $empleados->getNumeroEmpleado() ?></td>
                        <td><?= $empleados->getNombreCompleto() ?></td>
                        <td><?= $empleados->getCorreo() ?></td>
                        <td><?= $empleados->getTipoPlaza() ?></td>
                        <td><button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Detalle</button>
                            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">Modificar</button>
                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Borrar</button></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            
        </div>
    </div> 
    
    <div class="row-fluid">
        <div class="widget-box">
            <div class="widget-title bg_lg"><span class="icon"><i class="icon-signal"></i></span>
                <h5>Site Analytics</h5>
            </div>
            <div class="widget-content" >
                <div class="row-fluid">
                    <div class="span9">
                        <div class="chart"></div>
                    </div>
                    <div class="span3">
                        <ul class="site-stats">
                            <li class="bg_lh"><i class="icon-user"></i> <strong>2540</strong> <small>Total Users</small></li>
                            <li class="bg_lh"><i class="icon-plus"></i> <strong>120</strong> <small>New Users </small></li>
                            <li class="bg_lh"><i class="icon-shopping-cart"></i> <strong>656</strong> <small>Total Shop</small></li>
                            <li class="bg_lh"><i class="icon-tag"></i> <strong>9540</strong> <small>Total Orders</small></li>
                            <li class="bg_lh"><i class="icon-repeat"></i> <strong>10</strong> <small>Pending Orders</small></li>
                            <li class="bg_lh"><i class="icon-globe"></i> <strong>8540</strong> <small>Online Orders</small></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
</div>

