<div id="content-header">
    <div id="breadcrumb"> <a href="<?= $this->url('home') ?> " title="Panel" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="<?= $this->url('expedientes') ?>">Inventario Tienda</a></div>
    <h1><?= $this->titulo; ?></h1>
</div>


<div class="container-fluid">                 
    <hr>
    <?PHP
    echo $this->flashMessenger()
            ->setMessageOpenFormat('<div class="alert alert-info alert-block"> <a class="close" data-dismiss="alert" href="#">×</a><h1>El registro se ha Guardado!</h1>')
            ->setMessageSeparatorString('<p></p>')
            ->setMessageCloseString('</div>')
            ->render('success');
    ?>
    <?php
    echo $this->controlador;
    ?>
    <a class="btn btn-info" href="<?= $this->url('inventario-producto-nuevo') ?>"><i class="icon-plus-sign"></i> Nuevo</a>
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
            <h5>Data table</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Unidad Medida</th>
                        <th>Precio</th>                        
                        <th>Descripcion</th> 
                       
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->solicitud as $obj): ?>
                        <tr class="gradeX">
                            <td><?= $obj->getCodigo() ?></td>
                            <td><?= $obj->getNombre() ?></td>
                            <td><?= $obj->getUnidadMedida()  ?></td>
                            <td><?= $obj->getPrecio() ?></td>
                            <td><?= $obj->getDescripcion() ?></td> 
                            
                            

                        </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>