<?php
$form = $this->form;

$form->get('idSolicitud');

$form->get('RFC')->setAttributes([
    'class' => 'span3',
    'placeholder' => 'RFC'
]);

$form->get('nombrePaciente')->setAttributes([
    'class' => 'span5',
    'placeholder' => 'Ejemplo: Juan Perez',
]);

$form->get('Hombre')->setAttributes([
    'class' => 'span5 m-wrap',
    'placeholder' => 'Ejemplo: Nombre Apellido Pat Apellido Mat',
]);

$form->get('Mujer')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Ejemplo: 00/00/0000'
]);

$form->get('edad')->setAttributes([
    'class' => 'span2',
    'placeholder' => 'Ejemplo: 35'
]);

$form->get('nombreFamiliar')->setAttributes([
    'class' => 'span5',
    'placeholder' => 'Ejemplo: Nombre Apellido Pat Apellido Mat'
]);

$form->get('parentesco')->setAttributes([
    'class' => 'span4',
    'placeholder' => 'Seleccione parentesco'
]);

$form->get('telefono')->setAttributes([
    'class' => 'span4',
    'placeholder' => '(000) 000-0000'
]);

$form->get('domicilio')->setAttributes([
    'class' => 'span7',
    'placeholder' => 'Ejemplo: Direccion completa del familiar o pacinete'
]);

$form->get('motivoAtencion')->setAttributes([
    'class' => 'span7',
    'placeholder' => 'Ejemplo: Escribir el motivo de la atencion del paciente'
]);

$form->get('lesiones')->setAttributes([
    'class' => 'span7',
    'placeholder' => 'Ejemplo: Encaso de tener lesiones'
]);

$form->get('diacnostico')->setAttributes([
    'class' => 'span7',
    'placeholder' => 'Ejemplo: Diacnostico del paciente'
]);

$form->get('pronostico')->setAttributes([
    'class' => 'span7',
    'placeholder' => 'Ejemplo: Pronostico del paciente'
]);

$form->get('nombreMedico')->setAttributes([
    'class' => 'span7',
    'placeholder' => 'Ejemplo: Dr. José Aranda Martinez'
]);

$form->get('submit')->setAttributes(array('class' => 'btn btn-primary'));
$form->prepare();
?>

<div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="#">Pacientes</a> <a href="#" class="current">Solicitud de ingreso</a> </div>
    <h1><?= $this->titulo ?></h1>
</div>
<div class="container-fluid"><hr>    
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-pencil"></i> </span>
                    <h5><?= $this->subTitulo ?></h5>
                </div>
                <div class="widget-content nopadding">
                    <?= $this->form()->openTag($form); ?>
                    <div id="form-wizard-1" class="step"> 
                        <div class="control-group">
                            <?= $this->formLabel($form->get('RFC')); ?>
                            <div class="controls">                
                                <?= $this->formElement($form->get('RFC')); ?>
                                <?= $this->formElementErrors($form->get('RFC')); ?>
                                <div class="hint">(RFC Paciente)</div>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('nombrePaciente')); ?>
                            <div class="controls">                
                                <?= $this->formElement($form->get('nombrePaciente')); ?>
                                <?= $this->formElementErrors($form->get('nombrePaciente')); ?>
                                <!--<div class="hint">(PNG and JPG formats are allowed)</div>-->
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="checkboxes" class="control-label">Sexo:</label>
                            <div class="controls">
                                <div data-toggle="buttons-radio" class="btn-group">
                                    <button class="btn btn-info" type="button">Hombre</button>
                                    <button class="btn btn-info" type="button">Mujer</button>

                                </div>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('edad')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('edad')); ?>
                                <?= $this->formElementErrors($form->get('edad')); ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('nombreFamiliar')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('nombreFamiliar')); ?>
                                <?= $this->formElementErrors($form->get('nombreFamiliar')); ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('parentesco')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('parentesco')); ?>
                                <?= $this->formElementErrors($form->get('parentesco')); ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('telefono')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('telefono')); ?>
                                <?= $this->formElementErrors($form->get('telefono')); ?>
                                <div class="hint">(000) 000-0000</div>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('domicilio')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('domicilio')); ?>
                                <?= $this->formElementErrors($form->get('domicilio')); ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('motivoAtencion')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('motivoAtencion')); ?>
                                <?= $this->formElementErrors($form->get('motivoAtencion')); ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('lesiones')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('lesiones')); ?>
                                <?= $this->formElementErrors($form->get('lesiones')); ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <?= $this->formLabel($form->get('diacnostico')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('diacnostico')); ?>
                                <?= $this->formElementErrors($form->get('diacnostico')); ?>
                            </div>
                        </div>

                        <label for="checkboxes" class="control-label">Plan terapéutico:</label>
                        <div class="controls">
                            <div data-toggle="buttons-radio" class="btn-group">
                                <button class="btn btn-primary" type="button">Farmacoterapia</button>
                                <button class="btn btn-primary" type="button">Exámenes de laboratorio</button>
                                <button class="btn btn-primary" type="button">Psicología</button>
                                <button class="btn btn-primary" type="button">Consejería</button>
                                <button class="btn btn-primary" type="button">Canalización</button>
                            </div>
                        </div>
                        <div class="control-group">
                            <?= $this->formLabel($form->get('pronostico')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('pronostico')); ?>
                                <?= $this->formElementErrors($form->get('pronostico')); ?>
                            </div>
                        </div>
                         <div class="control-group">
                            <?= $this->formLabel($form->get('nombreMedico')); ?>
                            <div class="controls">
                                <?= $this->formElement($form->get('nombreMedico')); ?>
                                <?= $this->formElementErrors($form->get('nombreMedico')); ?>
                            </div>
                        </div>
  
                    <div class="form-actions">
                        <?= $this->formElement($form->get('submit')); ?>
                        <input id="back" class="btn btn-primary" type="reset" value="Back" />
                        <input id="next" class="btn btn-primary" type="submit" value="Next" />
                        <div id="status"></div>
                    </div>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
            <h5>Data table</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>Rendering engine</th>
                        <th>Browser</th>
                        <th>Platform(s)</th>
                        <th>Engine version</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="gradeX">
                        <td>Trident</td>
                        <td>Internet
                            Explorer 4.0</td>
                        <td>Win 95+</td>
                        <td class="center">4</td>
                    </tr>
                    <tr class="gradeC">
                        <td>Trident</td>
                        <td>Internet
                            Explorer 5.0</td>
                        <td>Win 95+</td>
                        <td class="center">5</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Trident</td>
                        <td>Internet
                            Explorer 5.5</td>
                        <td>Win 95+</td>
                        <td class="center">5.5</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Trident</td>
                        <td>Internet
                            Explorer 6</td>
                        <td>Win 98+</td>
                        <td class="center">6</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Trident</td>
                        <td>Internet Explorer 7</td>
                        <td>Win XP SP2+</td>
                        <td class="center">7</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Trident</td>
                        <td>AOL browser (AOL desktop)</td>
                        <td>Win XP</td>
                        <td class="center">6</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Firefox 1.0</td>
                        <td>Win 98+ / OSX.2+</td>
                        <td class="center">1.7</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Firefox 1.5</td>
                        <td>Win 98+ / OSX.2+</td>
                        <td class="center">1.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Firefox 2.0</td>
                        <td>Win 98+ / OSX.2+</td>
                        <td class="center">1.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Firefox 3.0</td>
                        <td>Win 2k+ / OSX.3+</td>
                        <td class="center">1.9</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Camino 1.0</td>
                        <td>OSX.2+</td>
                        <td class="center">1.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Camino 1.5</td>
                        <td>OSX.3+</td>
                        <td class="center">1.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Netscape 7.2</td>
                        <td>Win 95+ / Mac OS 8.6-9.2</td>
                        <td class="center">1.7</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Netscape Browser 8</td>
                        <td>Win 98SE+</td>
                        <td class="center">1.7</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Netscape Navigator 9</td>
                        <td>Win 98+ / OSX.2+</td>
                        <td class="center">1.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.0</td>
                        <td>Win 95+ / OSX.1+</td>
                        <td class="center">1</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.1</td>
                        <td>Win 95+ / OSX.1+</td>
                        <td class="center">1.1</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.2</td>
                        <td>Win 95+ / OSX.1+</td>
                        <td class="center">1.2</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.3</td>
                        <td>Win 95+ / OSX.1+</td>
                        <td class="center">1.3</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.4</td>
                        <td>Win 95+ / OSX.1+</td>
                        <td class="center">1.4</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.5</td>
                        <td>Win 95+ / OSX.1+</td>
                        <td class="center">1.5</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.6</td>
                        <td>Win 95+ / OSX.1+</td>
                        <td class="center">1.6</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.7</td>
                        <td>Win 98+ / OSX.1+</td>
                        <td class="center">1.7</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Mozilla 1.8</td>
                        <td>Win 98+ / OSX.1+</td>
                        <td class="center">1.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Seamonkey 1.1</td>
                        <td>Win 98+ / OSX.2+</td>
                        <td class="center">1.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Gecko</td>
                        <td>Epiphany 2.20</td>
                        <td>Gnome</td>
                        <td class="center">1.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Webkit</td>
                        <td>Safari 1.2</td>
                        <td>OSX.3</td>
                        <td class="center">125.5</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Webkit</td>
                        <td>Safari 1.3</td>
                        <td>OSX.3</td>
                        <td class="center">312.8</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Webkit</td>
                        <td>Safari 2.0</td>
                        <td>OSX.4+</td>
                        <td class="center">419.3</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Webkit</td>
                        <td>Safari 3.0</td>
                        <td>OSX.4+</td>
                        <td class="center">522.1</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Webkit</td>
                        <td>OmniWeb 5.5</td>
                        <td>OSX.4+</td>
                        <td class="center">420</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Webkit</td>
                        <td>iPod Touch / iPhone</td>
                        <td>iPod</td>
                        <td class="center">420.1</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Webkit</td>
                        <td>S60</td>
                        <td>S60</td>
                        <td class="center">413</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Opera 7.0</td>
                        <td>Win 95+ / OSX.1+</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Opera 7.5</td>
                        <td>Win 95+ / OSX.2+</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Opera 8.0</td>
                        <td>Win 95+ / OSX.2+</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Opera 8.5</td>
                        <td>Win 95+ / OSX.2+</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Opera 9.0</td>
                        <td>Win 95+ / OSX.3+</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Opera 9.2</td>
                        <td>Win 88+ / OSX.3+</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Opera 9.5</td>
                        <td>Win 88+ / OSX.3+</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Opera for Wii</td>
                        <td>Wii</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Nokia N800</td>
                        <td>N800</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Presto</td>
                        <td>Nintendo DS browser</td>
                        <td>Nintendo DS</td>
                        <td class="center">8.5</td>
                    </tr>
                    <tr class="gradeC">
                        <td>KHTML</td>
                        <td>Konqureror 3.1</td>
                        <td>KDE 3.1</td>
                        <td class="center">3.1</td>
                    </tr>
                    <tr class="gradeA">
                        <td>KHTML</td>
                        <td>Konqureror 3.3</td>
                        <td>KDE 3.3</td>
                        <td class="center">3.3</td>
                    </tr>
                    <tr class="gradeA">
                        <td>KHTML</td>
                        <td>Konqureror 3.5</td>
                        <td>KDE 3.5</td>
                        <td class="center">3.5</td>
                    </tr>
                    <tr class="gradeX">
                        <td>Tasman</td>
                        <td>Internet Explorer 4.5</td>
                        <td>Mac OS 8-9</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeC">
                        <td>Tasman</td>
                        <td>Internet Explorer 5.1</td>
                        <td>Mac OS 7.6-9</td>
                        <td class="center">1</td>
                    </tr>
                    <tr class="gradeC">
                        <td>Tasman</td>
                        <td>Internet Explorer 5.2</td>
                        <td>Mac OS 8-X</td>
                        <td class="center">1</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Misc</td>
                        <td>NetFront 3.1</td>
                        <td>Embedded devices</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeA">
                        <td>Misc</td>
                        <td>NetFront 3.4</td>
                        <td>Embedded devices</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeX">
                        <td>Misc</td>
                        <td>Dillo 0.8</td>
                        <td>Embedded devices</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeX">
                        <td>Misc</td>
                        <td>Links</td>
                        <td>Text only</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeX">
                        <td>Misc</td>
                        <td>Lynx</td>
                        <td>Text only</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeC">
                        <td>Misc</td>
                        <td>IE Mobile</td>
                        <td>Windows Mobile 6</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeC">
                        <td>Misc</td>
                        <td>PSP browser</td>
                        <td>PSP</td>
                        <td class="center">-</td>
                    </tr>
                    <tr class="gradeU">
                        <td>Other browsers</td>
                        <td>All others</td>
                        <td>-</td>
                        <td class="center">-</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


