<div id="content-header">
    <div id="breadcrumb"> <a href="<?= $this->url('home') ?> " title="Panel" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="<?= $this->url('expedientes') ?>">Expediente</a></div>
    <h1><?= $this->titulo; ?></h1>
</div>

<div class="container-fluid"> 

    <hr>
    <?PHP
    echo $this->flashMessenger()
            ->setMessageOpenFormat('<div class="alert alert-info alert-block"> <a class="close" data-dismiss="alert" href="#">×</a><h1>El registro se ha Guardado!</h1>')
            ->setMessageSeparatorString('<p></p>')
            ->setMessageCloseString('</div>')
            ->render('success');
    ?>
    <a class="btn btn-info" href="<?= $this->url('ingreso-nuevo') ?>"><i class="icon-plus-sign"></i> Nuevo</a>
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
            <h5>Data table</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>R.F.C</th>
                        <th>Nombre</th>
                        <th>Sexo</th>
                        <th>Edad</th>                        
                        <th>Familiar</th>                        
                        <th>Fecha</th>
                        <th>Estado</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    
                    <?php foreach ($this->objIngreso as $obj): ?>
                        <tr class="gradeX">
                            <td><?= $obj['rfc'] ?></td>
                            <td><?= $obj['nombre'] ?></td>
                            <td><?= $obj['sexo'] ?></td>
                            <td><?= $obj['edad'] ?></td>
                            <td><?= $obj['edad'] ?></td>
                            <td><?= $obj['edad'] ?></td>
                            <td><?= $obj['edad'] ?></td>
                            <td>
                                <a class="btn btn-primary" href="">Modificar</a>                                
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Borrar</button></td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
