<?php
$form = $this->form;

$form->get('idingreso');

$form->get('rfc')->setAttributes([
    'class' => 'span2 m-wrap',
    'placeholder' => 'RFC'
]);

$form->get('foto')->setAttributes([
    'class' => 'span2 m-wrap',
    'placeholder' => ''
]);
$form->get('nombre')->setAttributes([
    'class' => 'span5 m-wrap',
    'placeholder' => ''
]);
$form->get('sexo')->setAttributes([
    'class' => 'span50 m-wrap',
    'placeholder' => ''
]);
$form->get('fechaNac')->setAttributes([
    'class' => 'span5 m-wrap',
    'placeholder' => ''
]);
$form->get('edad')->setAttributes([
    'class' => 'span2 m-wrap',
    'placeholder' => ''
]);

$form->get('direccion')->setAttributes([
    'class' => 'span5 m-wrap',
    'placeholder' => ''
]);

$form->get('codigoPostal')->setAttributes([
    'class' => 'span2 m-wrap',
]);

$form->get('escolaridad')->setAttributes([
    'class' => 'span3 m-wrap',
    'placeholder' => ''
]);

$form->get('ocupacion')->setAttributes([
    'class' => 'span3 m-wrap',
    'placeholder' => ''
]);

$form->get('estadoCivil')->setAttributes([
    'class' => 'span3 m-wrap',
    'placeholder' => ''
]);


//$form->get('nacionalidad')->setAttributes([
//    'class' => 'span50',
//]);
//$form->get('municipio')->setAttributes([
//    'class' => 'span50',
//]);

$form->get('telefonoParticular')->setAttributes([
    'class' => 'span2 m-wrap',
]);
$form->get('celular')->setAttributes([
    'class' => 'span2 m-wrap',
]);
$form->get('telefonoTrabajo')->setAttributes([
    'class' => 'span2 m-wrap',
]);
$form->get('servicioMedico')->setAttributes([
    'class' => 'span2 m-wrap',
]);
$form->get('numeroServicio')->setAttributes([
    'class' => 'span2 m-wrap',
]);
$form->get('email')->setAttributes([
    'class' => 'span2 m-wrap',
]);

//$form->get('Voluntario')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('Involuntario')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('Obligatorio')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('domicilioParticular')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('institucionPublica')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('institucionPrivada')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('hospitalPsiquiatrico')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('centroRedaptacion')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('otros')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('otro')->setAttributes([
//    'class' => 'span10 m-wrap',
//]);
//$form->get('solo')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('amigo')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('vecino')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('familiar')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('dependencia')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('consecuencia')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('trastorno')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('criteriosAdmision')->setAttributes([
//    'class' => 'btn',
//]);
//$form->get('nombreFamiliar')->setAttributes([
//    'class' => 'span50 m-wrap',
//    'placeholder' => ''
//]);
//$form->get('direccionFamiliar')->setAttributes([
//    'class' => 'span50 m-wrap',
//    'placeholder' => ''
//]);
$form->get('numero')->setAttributes([
    'class' => 'span2 m-wrap',
    'placeholder' => ''
]);
//$form->get('colonia')->setAttributes([
//    'class' => 'span15 m-wrap',
//    'placeholder' => ''
//]);
//$form->get('municipioFamiliar')->setAttributes([
//    'class' => 'span15 m-wrap',
//    'placeholder' => ''
//]);



$form->get('btnGuardar')->setAttributes(array('class' => 'btn btn-primary'));
$form->prepare();
?>

<?= $this->form()->closeTag(); ?>
<div id="content-header">
    <div id="breadcrumb"> <a href="<?= $this->url('home'); ?>" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="<?= $this->url('expedientes'); ?>">Pacientes</a> <a href="#" class="current">Ingreso </a> </div>
    <h1><?= $this->titulo; ?></h1>
</div>

<div class="container-fluid">  
    <div id="message-text"></div>
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>DATOS DEL INTERNO</h5>
                </div>
                <div class="widget-content nopadding">
                    <?= $this->form()->openTag($form); ?>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('rfc')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('rfc')); ?> <a href="https://www.mi-rfc.com.mx/consulta-rfc-homoclave" class="btn btn-info" title="Consulta tu RFC." target="_blank"><i class="icon-th-large"></i></a>
                            <?= $this->formElementErrors($form->get('rfc')); ?>
                            <div id="cargando">
                            </div>
                            <div class="hint">
                                (RFC Paciente)</div>
                        </div>
                    </div>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('foto')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('foto')); ?> 
                            <?= $this->formElementErrors($form->get('foto')); ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('nombre')); ?>
                            <?= $this->formElementErrors($form->get('nombre')); ?>
                        </div>
                    </div>

                    <div class="control-group">                       
                        <label class="control-label">Sexo paciente:</label>
                        <div class="controls">                             
                            <?= $this->formElement($form->get('sexo')); ?>
                            <?= $this->formElementErrors($form->get('sexo')); ?>

                        </div>
                    </div>                     
                    <div class="control-group">
                        <?= $this->formLabel($form->get('fechaNac')); ?>
                        <div class="controls"> 
                            <div data-date="12-02-2012" class="input-append date datepicker">
                                <?= $this->formElement($form->get('fechaNac')); ?>
                                <span class="add-on"><i class="icon-th"></i></span>
                            </div>
                            <div class="hint">
                                (Formato: mm/dd/aaaa)
                            </div>
                            <?= $this->formElementErrors($form->get('fechaNac')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('edad')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('edad')); ?>
                            <?= $this->formElementErrors($form->get('edad')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('direccion')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('direccion')); ?>
                            <?= $this->formElementErrors($form->get('direccion')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('codigoPostal')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('codigoPostal')); ?>
                            <?= $this->formElementErrors($form->get('codigoPostal')); ?>

                        </div>
                    </div> 

                    <div class="control-group">
                        <?= $this->formLabel($form->get('escolaridad')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('escolaridad')); ?>
                            <?= $this->formElementErrors($form->get('escolaridad')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('ocupacion')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('ocupacion')); ?>
                            <?= $this->formElementErrors($form->get('ocupacion')); ?>

                        </div>
                    </div> 

                    <div class="control-group">
                        <?= $this->formLabel($form->get('estadoCivil')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('estadoCivil')); ?>
                            <?= $this->formElementErrors($form->get('estadoCivil')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('telefonoParticular')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('telefonoParticular')); ?>
                            <?= $this->formElementErrors($form->get('telefonoParticular')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('celular')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('celular')); ?>
                            <?= $this->formElementErrors($form->get('celular')); ?>

                        </div>
                    </div>
                    <div class="control-group">
                        <?= $this->formLabel($form->get('telefonoTrabajo')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('telefonoTrabajo')); ?>
                            <?= $this->formElementErrors($form->get('telefonoTrabajo')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('servicioMedico')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('servicioMedico')); ?>
                            <?= $this->formElementErrors($form->get('servicioMedico')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('numeroServicio')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('numeroServicio')); ?>
                            <?= $this->formElementErrors($form->get('numeroServicio')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('numero')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('numero')); ?>
                            <?= $this->formElementErrors($form->get('numero')); ?>

                        </div>
                    </div>     
                    <div class="control-group">
                        <?= $this->formLabel($form->get('email')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('email')); ?>
                            <?= $this->formElementErrors($form->get('email')); ?>

                        </div>
                    </div>         

                    <div class="form-actions">
                        <?= $this->formElement($form->get('btnGuardar')); ?>
                        <input id="back" class="btn btn-danger" type="reset" value="Cancelar" />
                        <div id="status"></div>
                    </div>
                    <?= $this->form()->closeTag(); ?>


                </div>
            </div>
        </div>
    </div>
</div>
</div>

