<?php
$form = $this->form;

$form->get('idingreso');

$form->get('tienesFecha')->setAttributes([
    'class' => 'span50 m-wrap',
    'required' => true,
]);

$form->get('fecha')->setAttributes([
    'class' => 'span2 m-wrap',
    'placeholder' => ''
]);


$form->get('rfc')->setAttributes([
    'class' => 'span2 m-wrap',
    'required' => true,
    'placeholder' => 'RFC'
]);

$form->get('foto')->setAttributes([
    'class' => 'span2 m-wrap',
    'placeholder' => ''
]);
$form->get('nombre')->setAttributes([
    'class' => 'span5 m-wrap',
    'required' => true,
    'placeholder' => ''
]);
$form->get('sexo')->setAttributes([
    'class' => 'span50 m-wrap',
    'required' => true,
    'placeholder' => ''
]);
$form->get('fechaNac')->setAttributes([
    'class' => 'span5 m-wrap',
    'required' => true,
    'placeholder' => ''
]);
$form->get('edad')->setAttributes([
    'class' => 'span2 m-wrap',
    'required' => true,
    'placeholder' => ''
]);

$form->get('escolaridad')->setAttributes([
    'class' => 'span3 m-wrap',
    'required' => true,
    'placeholder' => ''
]);

$form->get('ocupacion')->setAttributes([
    'class' => 'span3 m-wrap',
    'required' => true,
    'placeholder' => ''
]);

$form->get('estadoCivil')->setAttributes([
    'class' => 'span3 m-wrap',
    'required' => true,
    'placeholder' => ''
]);

$form->get('telefonoPp')->setAttributes([
    'class' => 'span2 mask text',
    'placeholder' => ''
]);

$form->get('telefonoPt')->setAttributes([
    'class' => 'span2 mask text',
    'placeholder' => ''
]);

$form->get('celular')->setAttributes([
    'class' => 'span2 mask text',
    'placeholder' => ''
]);


$form->get('nacionalidad')->setAttributes([
    'required' => true,
    'class' => 'span5',
]);

$form->get('municipio')->setAttributes([
    'required' => true,
    'class' => 'span5',
]);


$form->get('servicioMedico')->setAttributes([
    'required' => true,
    'class' => 'span2 m-wrap',
//    'required' => true,
]);
$form->get('numeroServicio')->setAttributes([
    'class' => 'span2 m-wrap',
]);
$form->get('email')->setAttributes([
    'class' => 'span2 m-wrap',
]);

$form->get('tipo')->setAttributes([
    'class' => 'span2 m-wrap',
    'required' => true,
]);

$form->get('referencia')->setAttributes([
    'class' => 'span2 m-wrap',
    'required' => true,
]);

$form->get('otro')->setAttributes([
    'class' => 'span2 m-wrap',

]);

$form->get('acude')->setAttributes([
    'class' => 'span2 m-wrap',
    'required' => true,
]);

$form->get('parentesco')->setAttributes([
    'class' => 'span3 m-wrap',
    'required' => true,
]);

$form->get('adulo')->setAttributes([
    'class' => 'span50 m-wrap',
    'required' => true,
]);

$form->get('drogasAlcohol')->setAttributes([
    'class' => 'span50 m-wrap',
    'required' => true,
]);
$form->get('consecunciaConsumo')->setAttributes([
    'class' => 'span50 m-wrap',
    'required' => true,
]);
$form->get('mental')->setAttributes([
    'class' => 'span50 m-wrap',
    'required' => true,
]);
$form->get('criteriosAdmision')->setAttributes([
    'class' => 'span50 m-wrap',
    'required' => true,
]);


$form->get('numero')->setAttributes([
    'class' => 'span2 m-wrap',
    'placeholder' => ''
]);

///////Familiares////////
$form->get('nombreFam')->setAttributes([
    'class' => 'span3 m-wrap',
    'required' => true,
    'placeholder' => ''
]);

$form->get('domicilioFam')->setAttributes([
    'class' => 'span4 m-wrap',
    'required' => true,
    'placeholder' => ''
]);
$form->get('numeroFam')->setAttributes([
    'class' => 'span1 m-wrap',
    'required' => true,
    'placeholder' => ''
]);
$form->get('coloniaFam')->setAttributes([
    'class' => 'span2 m-wrap',
    'required' => true,
    'placeholder' => ''
]);

$form->get('telefonoParticularFam')->setAttributes([
    'class' => 'span2 mask text',
    'required' => true,
    'placeholder' => ''
]);
$form->get('celularFam')->setAttributes([
    'class' => 'span2 mask text',
    'required' => true,
    'placeholder' => ''
]);


$form->get('btnGuardar')->setAttributes(array('class' => 'btn btn-primary'));
$form->prepare();
?>

<?= $this->form()->closeTag(); ?>
<div id="content-header">
    <div id="breadcrumb"> <a href="<?= $this->url('home'); ?>" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="<?= $this->url('expedientes'); ?>">Pacientes</a> <a href="#" class="current">Ingreso </a> </div>
    <h1><?= $this->titulo; ?></h1>
</div>

<div class="container-fluid">  
    <div id="message-text"></div>
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <?= $this->form()->openTag($form); ?>
            <div class="widget-box">                
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>DATOS DEL PACIENTE</h5>
                </div>
                <div class="widget-content nopadding"> 
                    <div class="control-group">
                        <label class="control-label">Tienes fecha de Ingreso</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('tienesFecha')); ?> 
                            <?= $this->formElementErrors($form->get('tienesFecha')); ?>  
                        </div>
                    </div>
              
                    <div class="control-group">
                        <?= $this->formLabel($form->get('fecha')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('fecha')); ?> 
                            <?= $this->formElementErrors($form->get('fecha')); ?>
                            <div class="hint">
                                (año/mes/dia)</div>
                        </div>
                         
                    </div>
                    
             
                    <div class="control-group">
                        <?= $this->formLabel($form->get('rfc')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('rfc')); ?> <a href="https://www.mi-rfc.com.mx/consulta-rfc-homoclave" class="btn btn-info" title="Consulta tu RFC." target="_blank"><i class="icon-th-large"></i></a>
                            <?= $this->formElementErrors($form->get('rfc')); ?>
                            <div id="cargando">
                            </div>
                            <div class="hint">
                                (RFC Paciente)</div>
                        </div>
                    </div>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('foto')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('foto')); ?> 
                            <?= $this->formElementErrors($form->get('foto')); ?>
                        </div> 

                    </div>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('nombre')); ?>
                            <?= $this->formElementErrors($form->get('nombre')); ?>
                        </div>
                    </div>

                    <div class="control-group">                       
                        <label class="control-label">Sexo paciente:</label>
                        <div class="controls">                             
                            <?= $this->formElement($form->get('sexo')); ?>
                            <?= $this->formElementErrors($form->get('sexo')); ?>

                        </div>
                    </div>                     
                    <div class="control-group">
                        <?= $this->formLabel($form->get('fechaNac')); ?>
                        <div class="controls"> 
                            <div data-date="12-02-2012" class="input-append date datepicker">
                                <?= $this->formElement($form->get('fechaNac')); ?>
                                <span class="add-on"><i class="icon-th"></i></span>
                            </div>
                            <div class="hint">
                                (Formato: mm/dd/aaaa)
                            </div>
                            <?= $this->formElementErrors($form->get('fechaNac')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('edad')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('edad')); ?>
                            <?= $this->formElementErrors($form->get('edad')); ?>

                        </div>
                    </div> 



                    <div class="control-group">
                        <?= $this->formLabel($form->get('escolaridad')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('escolaridad')); ?>
                            <?= $this->formElementErrors($form->get('escolaridad')); ?>

                        </div>
                    </div> 

                    <div class="control-group">
                        <?= $this->formLabel($form->get('ocupacion')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('ocupacion')); ?>
                            <?= $this->formElementErrors($form->get('ocupacion')); ?>
                        </div>
                    </div> 

                    <div class="control-group">
                        <?= $this->formLabel($form->get('estadoCivil')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('estadoCivil')); ?>
                            <?= $this->formElementErrors($form->get('estadoCivil')); ?>

                        </div>
                    </div> 

                    <div class="control-group">
                        <?= $this->formLabel($form->get('telefonoPp')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('telefonoPp')); ?>
                            <?= $this->formElementErrors($form->get('telefonoPp')); ?>

                        </div>
                    </div> 

                    <div class="control-group">
                        <?= $this->formLabel($form->get('telefonoPt')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('telefonoPt')); ?>
                            <?= $this->formElementErrors($form->get('telefonoPt')); ?>

                        </div>
                    </div> 

                    <div class="control-group">
                        <?= $this->formLabel($form->get('celular')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('celular')); ?>
                            <?= $this->formElementErrors($form->get('celular')); ?>

                        </div>
                    </div> 

                    <div class="control-group">
                        <?= $this->formLabel($form->get('servicioMedico')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('servicioMedico')); ?>
                            <?= $this->formElementErrors($form->get('servicioMedico')); ?>
                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('numeroServicio')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('numeroServicio')); ?>
                            <?= $this->formElementErrors($form->get('numeroServicio')); ?>

                        </div>
                    </div> 
                    <div class="control-group">
                        <?= $this->formLabel($form->get('numero')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('numero')); ?>
                            <?= $this->formElementErrors($form->get('numero')); ?>

                        </div>
                    </div>  

                    <div class="control-group">
                        <?= $this->formLabel($form->get('email')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('email')); ?>
                            <?= $this->formElementErrors($form->get('email')); ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('municipio')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('municipio')); ?>
                            <?= $this->formElementErrors($form->get('municipio')); ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('nacionalidad')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('nacionalidad')); ?>
                            <?= $this->formElementErrors($form->get('nacionalidad')); ?>
                        </div>
                    </div>

                </div>
            </div>
            <div class="widget-box">                
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>COMO INGRESA EL USUARIO</h5>
                </div>
                <div class="widget-content nopadding">
                    <div class="control-group">
                        <label class="control-label">Tipo de ingreso:</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('tipo')); ?> 
                            <?= $this->formElementErrors($form->get('tipo')); ?>                            

                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Referencia del Usuario:</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('referencia')); ?> 
                            <?= $this->formElementErrors($form->get('referencia')); ?>  
                        </div>
                    </div>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('otro')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('otro')); ?>
                            <?= $this->formElementErrors($form->get('otro')); ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Con quien acude:</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('acude')); ?> 
                            <?= $this->formElementErrors($form->get('acude')); ?>  
                        </div>
                    </div>

                    <div class="control-group">
                        <?= $this->formLabel($form->get('parentesco')); ?>
                        <div class="controls">                
                            <?= $this->formElement($form->get('parentesco')); ?>
                            <?= $this->formElementErrors($form->get('parentesco')); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="widget-box">                
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>CRITERIOS DE INCLUSION</h5>
                </div>
                <div class="widget-content nopadding">

                    <div class="control-group">
                        <label class="control-label">Es mayor de edad:</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('adulo')); ?> 
                            <?= $this->formElementErrors($form->get('adulo')); ?>  
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Presenta un nivel de dependencia al alcohol o drogas:</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('drogasAlcohol')); ?> 
                            <?= $this->formElementErrors($form->get('drogasAlcohol')); ?>  
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Consecuencia asociada al consumo:</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('consecunciaConsumo')); ?> 
                            <?= $this->formElementErrors($form->get('consecunciaConsumo')); ?>  
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Mental o psiquiátrico que le impida beneficiarse del tratamiento:</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('mental')); ?> 
                            <?= $this->formElementErrors($form->get('mental')); ?>  
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">El usuario cumple con todos los criterios de admisión al tratamiento:</label>
                        <div class="controls">                
                            <?= $this->formElement($form->get('criteriosAdmision')); ?> 
                            <?= $this->formElementErrors($form->get('criteriosAdmision')); ?>  
                        </div>
                    </div>
                </div>
            </div>

        <div class="widget-box">                
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>DATOS DEL REPRESENTANTE LEGAL</h5>
            </div>
            <div class="widget-content nopadding">                    
                <div class="control-group">
                    <?= $this->formLabel($form->get('nombreFam')); ?>
                    <div class="controls">                
                        <?= $this->formElement($form->get('nombreFam')); ?> 
                        <?= $this->formElementErrors($form->get('nombreFam')); ?>
                    </div>
                </div>
            </div>
            <div class="widget-content nopadding">                    
                <div class="control-group">
                    <?= $this->formLabel($form->get('domicilioFam')); ?>
                    <div class="controls">                
                        <?= $this->formElement($form->get('domicilioFam')); ?> 
                        <?= $this->formElementErrors($form->get('domicilioFam')); ?>
                    </div>
                </div>
            </div>
            <div class="widget-content nopadding">                    
                <div class="control-group">
                    <?= $this->formLabel($form->get('numeroFam')); ?>
                    <div class="controls">                
                        <?= $this->formElement($form->get('numeroFam')); ?> 
                        <?= $this->formElementErrors($form->get('numeroFam')); ?>
                    </div>
                </div>
            </div>
            <div class="widget-content nopadding">                    
                <div class="control-group">
                    <?= $this->formLabel($form->get('coloniaFam')); ?>
                    <div class="controls">                
                        <?= $this->formElement($form->get('coloniaFam')); ?> 
                        <?= $this->formElementErrors($form->get('coloniaFam')); ?>
                    </div>
                </div>
            </div>
            <div class="widget-content nopadding">                    
                <div class="control-group">
                    <?= $this->formLabel($form->get('telefonoParticularFam')); ?>
                    <div class="controls">                
                        <?= $this->formElement($form->get('telefonoParticularFam')); ?> 
                        <?= $this->formElementErrors($form->get('telefonoParticularFam')); ?>
                    </div>
                </div>
            </div>
            <div class="widget-content nopadding">                    
                <div class="control-group">
                    <?= $this->formLabel($form->get('celularFam')); ?>
                    <div class="controls">                
                        <?= $this->formElement($form->get('celularFam')); ?> 
                        <?= $this->formElementErrors($form->get('celularFam')); ?>
                    </div>
                </div>
            </div>

        </div>
        <div class="form-actions">
            <?= $this->formElement($form->get('btnGuardar')); ?>
            <input id="back" class="btn btn-danger" type="reset" value="Cancelar" />
            <div id="status"></div>
        </div>  
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
</div>


